manifestVersion: 1
id: esphome
category: Automation
name: ESPHome
version: "2023.2.4"
tagline: Интеллектуальное управление всеми вашими устройствами ESP8266/ESP32
description: >-
  ESPHome — это система для управления вашими ESP8266/ESP32 с помощью простых, но мощных файлов конфигурации и удаленного управления ими через системы домашней автоматизации.
developer: ESPHome
website: https://esphome.io
dependencies: []
repo: https://github.com/esphome/esphome
support: https://community.home-assistant.io/c/esphome
port: 6052
gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
path: ""
defaultUsername: ""
defaultPassword: ""
torOnly: false
releaseNotes: >-
  Этот выпуск обновляет ESPHome с версии 2022.6.2 до 2023.2.4. Полный список новых функций, поддержка новых компонентов, критические изменения и исправления ошибок для версий между 2022.6.2 и 2023.2.4 можно найти здесь: https://github.com/esphome/esphome/releases.

   Примечания к выпуску версии 2023.2.4:

   - Набор BL0939 state_class для датчиков энергии

   - исправить паритет тегов wiegand

   - Исправлено несколько remote_receivers с триггерами esphome#4477 by @jesserockz

submitter: ShonP40
submission: https://github.com/getumbrel/umbrel-apps/pull/43
